FROM python:3.11-slim AS base

ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY src ./src
COPY scripts ./scripts
COPY config ./config

COPY pyproject.toml ./
RUN pip install --upgrade pip && pip install . --no-cache-dir

CMD ["python", "scripts/train.py"]
